### ISSUE TITLE
Allow icon to be positioned with margin without being rotated

### ISSUE THREAD

**Issue by hokei** [NYPL/nypl-design-system#124]
### Description of issue:
Right now the positioning of icons is tied to their rotation.  (see `IconLink` and the `download` link in `EditionCard`. This should not be the case.)

**Comment by helenvholmes** [comment]
We're using css to rotate stuff like arrows
1:28
< > ^ v would all be one svg, for example, just rotated with a CSS transform
1:28
Right now though we rotate them based on their position (left, right) of whatever they're bundled with
1:28
But you should be able to position the icon to the left or right or something without it rotating.
1:29
Since Crystal opened the ticket, I'll be sure to bring it up in triage, just to make sure this is still happening.
