### ISSUE TITLE
Remove mandatory IDs

### ISSUE THREAD

**Issue by kristojorg** [NYPL/nypl-design-system#219]
This applies across many components. Unless there is a specific reason that IDs are required (why are they required?), we should make these props optional. It becomes a pain pretty quickly when using the components to have to pass IDs, especially when rendering components dynamically. If there is a reason these are required, though, I'm all ears.

**Comment by helenvholmes** [comment]
Most mandatory ids are coming from a period when we were trying to take a heavier hand in consumer accessibility, which over time we realized wasn't possible. (An example of the kind of documentation we were working off of can be found [here](http://themetronome.co/components/mf-47-input/?fresh=true).) I can't anticipate off the top of my head any reason why we can't make them all optional going forward, unless @hokei has some insight that I don't.

**Comment by kristojorg** [comment]
Ah makes sense yea. 

I would also personally rename them to simply `id` unless there are multiple subcomponents that need to be `id`'d.

**Comment by helenvholmes** [comment]
#220 might run into that @kristojorg—here are the [accessibility specs](http://themetronome.co/components/mf-200-search-bar/?fresh=true) we received for Search Bar. But otherwise yeah, that sounds fine.

**Comment by hokei** [comment]
I am of the opinion that everything (especially everything that is interactable) should have an id.  There are two reasons - 
1) generating keys off of an id is much easier.  
2) ids make it easier to test everything - QA has asked for ids so that they can better automate stuff.

But I know where you're coming from re: currently ids are really hard to work with.  
I'm hoping 
1) to be able to have each of the components in DS generate ids for their children in the future, so all you need to pass it is like, "id=searchbar" and then searchBar can generate an id for its button, like "searchbar-submitbutton" or something.  That's not here yet.  

2) To make it so that `props` checks for ids but you don't need to pass them in, I've proposed doing something like this:  https://github.com/NYPL/nypl-design-system/issues/191 -- I'd love your thoughts on this.  I've only skimmed the `SearchBar Props and Types` issue, but I think we're trying to solve the same big issue.

**Comment by helenvholmes** [comment]
I think we're all in agreement that everything should continue having IDs, just that they shouldn't be required on very atomic elements (button, input, label, etc.) and instead be optional.

Something like SearchBar (#220) could make subelement IDs required since it is combining elements in a specific way that would have accessibility requirements on it. Going off of @hokei's suggestion in #191, you'd make the ID on Searchbar required whereas on the input/label/buttons it was consuming, id (and aria-label, aria-labelledby) would be optional.

If people feel good about what I'm proposing here, I think we can turn this into a ticket that tracks work, namely making ids optional on:

- Button
- Label
- Textfield
- Input
- Select
- ?? anything else I'm missing?

**Comment by hokei** [comment]
Just to make sure we're all on the same page, I think `id` should be required on the `props` object of all the things you listed below, but optional on the `options` object. 

I think maybe for now we can make the ids optional on the `SearchBar` component, but eventually we are going to want to generate the SearchBar > Button and SearchBar > Input (etc etc) off of the SearchBar id, so eventually they will be required.  

(Since required -> optional is not a breaking change, but optional -> required is, I have a slight preference for requiring them out the gate so we're not asking people who have completed their work to go back and re-do it)

**Comment by kristojorg** [comment]
Okay, a few thoughts here:

> 1. generating keys off of an id is much easier.

Keys for in an array you mean? I'm curious when the DS is doing this for you and if it is, when is there not some other data (like an option name) to generate an ID? This seems like an edge case that shouldn't make _every_ component require an ID.

> 2. ids make it easier to test everything - QA has asked for ids so that they can better automate stuff.

It certainly does make it easier to test. But consider the purpose of testing: to make sure the application works as intended for the user. Users don't navigate the dom via IDs. They're looking for an input, for a button with a certain label, for a heading, etc. This, imo, is how tests should query the dom... otherwise you're really testing an implementation detail: "is there a node with the id searchbar-button". 

It also makes the tests more flaky. If a dev comes along and changes that ID or otherwise changes the DOM structure, it could still work exactly the same, but now all of the tests for that code would fail. This is actually compounded by the idea to generate ids within the DS. Then, you're actually testing implementation details of a dependency. Changing any of those generated IDs would break tests for consumers, even if the code still works exactly the same. 

Finally, and most importantly for NYPL, querying the dom with ids isn't going to provide any assurance of accessibility, whereas eg querying the dom via aria labels or text or node roles does provide that confidence. If you can't query the node by one of those, it's probably not accessible...

> 1. to be able to have each of the components in DS generate ids for their children in the future, so all you need to pass it is like, "id=searchbar" and then searchBar can generate an id for its button, like "searchbar-submitbutton" or something.  That's not here yet.

How can I guarantee that my IDs are unique? What if I make a `submitButton` ID and then another dev makes another `submitButton` id somewhere else? 

Overall, in my experience, adding IDs to dom elements should only be done in order to query an element within the application (which is what the id attr is meant for). I also know I have no influence over NYPL testing practices, but the fact that tests are written based on IDs would be a red flag to me that the confidence provided by those tests isn't actually worth the cost of developing and maintaining them.

Just wanted to give y'all my frank opinion on this so that it's recorded, I don't expect you to make a major change to your development practices based on my input, but just give it a ponder.

**Comment by helenvholmes** [comment]
I actually thought it would the opposite of what you said, @hokei—I'm going to mark this as a "Planning" ticket so we can make certain we feel good about everything going forward on Thursday. Sorry if this blocks your work in the meantime, @kristojorg 😔

**Comment by kristojorg** [comment]
No no worries! I’m actually not having much trouble converting CPW to the new designs using the components I already developed and just changing their styles a bit. So this isn’t a big issue for me right now :) and getting this right will make it easier to replace the CPW components with DS components when the time comes

**Comment by helenvholmes** [comment]
@kristojorg phew! Let's get into it Thursday then over video, I think that will get us further ahead than the conversation here (hopefully)

**Comment by hokei** [comment]
> How can I guarantee that my IDs are unique? What if I make a submitButton ID and then another dev makes another submitButton id somewhere else?

The hope was that the new ids would be generated based on the parent id, and the parent would id would be passed in by the consumer, and be unique.  So, there would only ever be one thing called "main-searchbar" which means there would only be one thing called "main-searchbar-input".  That was kind of the lines of my thinking, anyway.

All of what you're saying makes a lot of sense.  In that case I think it's ok to make ids optional (or, even better, to group them under `attributes` or whatever thing we're going to use as a catch-all to pass extra props through). 

You make a good point about testing via ids.  I have some negotiating ability so I'll bring it up again with them.  

(We should still figure out how to generate keys if a component has to create a list of children.  I don't think we have many of those, but `UnorderedList` might currently be implemented this way) 
This is super useful information to know though, so I'm super thankful!

**Comment by kristojorg** [comment]
Okay, that all makes sense to me! 

If you want to show the QA team an example not relying on IDs, the CPW tests are (almost) all queried by text content or aria label or role, so might be helpful.

In the case of keys for a UL, what do you think about letting the consumer create the component directly, and thus key the elements themselves? eg the following would be how the consumer could use the `Ul` and `Li` elements in the DS, thus eliminating the need to pass props through the `Ul` that are ultimately bound for the `Li` (like keys, or custom styles):
```js
<DS.Ul>
  {myItems.map(item => <DS.Li key={item.id} className="blueTextColor">{item.name}</DS.Li>}
</DS.Ul>
```
Ignore my bad className haha, just an example
