### ISSUE TITLE
Accordion story and implementation

### ISSUE THREAD

**Issue by EdwinGuzman** [NYPL/nypl-design-system#290]
### Component in question:
- Accordion.

### Description of issue:
- I'm going to use it in the Library Card app but the story is broken. It's a small fix so I can fix that.

- On a larger topic that may warrant a different ticket, when testing out the LCA without javascript, the accordion component doesn't work. This makes sense as it depends on javascript and the `onClick` handler to open and close the accordion. I was thinking maybe a CSS-only solution would be helpful in this case? I just want to get a feel and start a discussion on this as getting the app to work without javascript is not on its phase 1 release.

Here's an example: https://codepen.io/raubaca/pen/PZzpVe

**Comment by helenvholmes** [comment]
Thanks for identifying this and the suggestions. I like the idea of a CSS-only solution for the Accordion. I've seen people use checkboxes for this in the past since it natural handles a boolean state, which I think works pretty well.

We maybe should consider the same for the Modal, if we do this for Accordion.
