### ISSUE TITLE
Security Policy

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#313]
[Slack discussion](https://nypl.slack.com/archives/C1K983U1E/p1596815314082400)

**Comment by hokei** [comment]
After talking with Leonard:  

We should have one, but it can be pretty simple (file an issue and we will follow up for sensitive details or ask us on Slack) 

NYPL as a whole doesn't have one, but very few NYPL projects are like design system (aka used by other developers instead of used by consumers).

**Comment by helenvholmes** [comment]
I like that, that sounds good.

**Comment by helenvholmes** [comment]
Set something up in `.github/`, so we're all set.
