### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#480]
### Description of issue:
- I currently run releases every time someone merges to `development`
- I think it's time to begin bundling releases
- Should we squash and merge commits so all commits are associated with a single Github Issue # for context?
- Probably biweekly for now?

**Comment by hokei** [comment]
From planning:  Because sometimes DS bugfixes need to be released quickly, and a lot of those bugfixes cannot wait 1-2 weeks, we should continue to release ad-hoc

Release should be initiated by the user who merged the commit, when they need the release.  

For Product Monthlies, we should create a summary of progress since the last monthly.

**Comment by hokei** [comment]
I will update the wiki to propose squash-merging before development and also detail that the person who needs the update should run the release.

**Comment by helenvholmes** [comment]
I've updated the https://github.com/NYPL/nypl-design-system/wiki/How-to-Run-a-Release. Closing this out
