### ISSUE TITLE
Breaking changes in patch releases

### ISSUE THREAD

**Issue by AntonOfTheWoods** [NYPL/nypl-design-system#733]
### Description of issue:
The latest patch release (0.25.1) appears to have introduced a number of breaking changes, at least via commit 72aad961d3. Can you confirm that you are not using semver, and that non-nypl users should pin to exact versions as a rule?

If this repo is not intended to be used outside of NYPL codebases, would you accept a PR making this clearer at the top of the readme?

### Component in question (if applicable):
- React components

**Comment by EdwinGuzman** [comment]
Hi, currently, this Design System does not have a 1.0.0 stable release so every release we make is a breaking change release. This is the expectation inside of NYPL until we get to 1.0.0. We loosely follow semver but we'll strictly follow it once 1.0.0 is released.

1. Yes, it would be helpful to pin to exact versions if an existing version has all you need.
2. If you want updated components, then expect breaking changes (mostly minor unless otherwise noted in the CHANGELOG).

This repo is intended to be used by anyone and not just NYPL. The biggest breaking change version we released is actually 0.25.0. This version introduced Chakra UI into the codebase and updated how we create components. You can read about it here: https://nypl.github.io/nypl-design-system/storybook-static/?path=/story/chakra-ui--page

If something there is unclear, please do let us know. That being said, the README is slightly out-of-date so I'll make an update. I'll also add a migration guide from < 0.25.0 to >= 0.25.0. Expect this next release on 10/28.

**Comment by AntonOfTheWoods** [comment]
Thanks for the detailed comments!
