### ISSUE TITLE
Document a git and release flow

### ISSUE THREAD

**Issue by hokei** [NYPL/nypl-design-system#81]
The "git flow" we're currently following is as follows:  

- Do development work on a feature branch
- Merge into `development` 
- Manually bump and publish to npm ad-hoc 

We could either do: 
- tag with releases.  This will involve pushing package bumps to tags and making `NO-REF_Package_Bump` PRs. 
- publish from development manually via command line. 

The main problem I see with this is that there's an extra set of PR/Reviews.  It's easy for members on the same team, but might be unnecessary waiting if our schedules don't align (which they ... often don't haha) 

We could push the package_bump commit directly to development.  This in theory should not cause problems, but is blasphemous from a git/feature branching/workflow perspective.  

Or we can: 
- maintain development and master branches.  
- When releases happen (in the future, these will be scheduled.  Currently, they happen ad-hoc), merge from development to master.
- This kicks off a build - everything could be done automatically, I think - there should be a way to script a package bump, a tag, and a publish to NPM on merge.  (git-hooks?) Are there other places in the org does this and documents it?  

I haven't done this, but it seems like the "most correct" solution to me.

**Comment by hokei** [comment]
@EdwinGuzman thoughts?

**Comment by EdwinGuzman** [comment]
I'm not sure I understand what `NO-REF_Package_Bump` means. 
I like the idea that you can bump the version, tag it, and publish to npm when a merge happens to the master branch, but I'm not aware of how to do this.

I can tell you the git flow @adriana-alter and I follow in our projects, which is similar to what you do now. For some context: there's the `circulation` repo which installs a `circulation-web` npm app. As you can imagine, whenever a bug fix or feature gets added to `circulation-web`, we must deploy a new version and then install it on `circulation`, so the schedule for publishing to npm is ad-hoc and this is fine.

* `master` is our production-ready branch
* branch off `master` into a feature branch and work there
* bump the version in _this_ feature branch and update the changelog. This way, the other developer is also aware that a new version is being published and _what_ is being published in that release.
* when the feature branch is merged into master, publish a new version.

We skip the "package_bump commit" process and attach that to our current feature branch. I think this works well because, like you said, having a separate branch PR just for a version branch can slow things down.

Maybe the problem now is that the `development` branch is the "main" branch and a production name branch should be used. What confused me was that there was a release done and then those changes were being merged into `development`. So, there doesn't seem to be a stable branch. I think you may want to first settle into a flow that makes sense for the naming convention you want to use, and then you can work on automating the release process.

**Comment by hokei** [comment]
From our offline talk:  

- `development` is main branch.  It should reflect what is published to `npm`.  
When creating the first ticket after a publish, we should create a new branch and bump the version.  Add to changelog here.  
- For now, we will generally publish after every ticket.  We will revisit this if we get to regular releases - in that case I think it will sense to maintain a "working/development" and a "release/master" branch.  
- When publishing via Lerna, don't bump versions (they've already been bumped in the branch).

**Comment by helenvholmes** [comment]
Closing this out, I think this has been solved.
